dist: xenial

git:
  depth: 1

install: true

stages:
  - verify
  - name: build-docs

jobs:
  include:
    - stage: "verify"
      script: docker-compose run --rm verify bash -c "bundle install && bundle exec rubocop"

    - stage: "verify"
      script: docker-compose run --rm verify bash -c "bundle install && bundle exec rspec"


    - stage: "build-docs"
      script:
        - set -e
        - |
          export IMG_TAG=`echo $TRAVIS_BRANCH | sed -e 's/[\/]/-/g' | sed -e 's/[\#]//g'`
          export CI_COMMIT_SHORT_SHA=$(git rev-parse --short HEAD)
          docker build -t teracy/teracy-dev-docs:$IMG_TAG docs
        # only if DOCKER_USERNAME, DOCKER_PASSWORD specified
        - |
          if [ -n "$DOCKER_USERNAME" ] && [ -n "$DOCKER_PASSWORD" ]; then
            echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
            docker tag teracy/teracy-dev-docs:$IMG_TAG $DOCKER_USERNAME/teracy-dev-docs:$IMG_TAG-$CI_COMMIT_SHORT_SHA
            docker push $DOCKER_USERNAME/teracy-dev-docs:$IMG_TAG-$CI_COMMIT_SHORT_SHA
          fi
