
# teracy-dev related settings
teracy-dev:
  require_version: ">= 0.6.0-a8"
  # location sync
  location:
    git:
      remote:
        origin: https://github.com/teracyhq/dev.git
      branch: v0.6.0-a8
    sync: false # disabled by default, should be enabled by teracy-dev-entry when needed
  extensions:
    - _id: "kernel-core"
      _id_deprecated: "0"
      path:
        lookup: extensions # we can configure where to lookup for the extension, "extensions" by default if no configured
        extension: teracy-dev-core # extension_path, we'll lookup the extension by its lookup_path + extension_path
      location: # auto download the extension into the lookup_path
        git:
          remote:
            origin: https://github.com/teracyhq-incubator/teracy-dev-core.git
          branch: v0.4.0
      require_version: ">= 0.4.0"
      enabled: true # when true, extension will be auto-downloaded if not available yet and will load this extension to be used
    # extension must have manifest.yaml file to describe its name, version and optional description
    # optional: config_default.yaml, teracy-dev-ext.rb will be auto loaded if available
  # support for teracy-dev-entry auto update
  entry_location:
    git:
      remote:
        origin:
      branch:
    sync: false # disabled by default, should be enabled by teracy-dev-entry when needed

# vagrant related settings
vagrant: {}

# default settings for all nodes
default: {}

# specific nodes, each node will override the default
nodes: []
