apiVersion: skaffold/v1beta10
kind: Config
build:
  artifacts:
    - image: teracy/teracy-dev-docs-dev
      sync:
        manual:
        - src: '**/*.rst'
          dest: .
      docker:
        dockerfile: Dockerfile-dev
  tagPolicy:
    gitCommit:
      variant: TreeSha

deploy:
  helm:
    releases:
    - name: teracy-dev-docs-dev
      chartPath: helm-charts/teracy-dev-docs-dev
      values:
        image: teracy/teracy-dev-docs-dev
      valuesFiles:
      - override.yaml
      imageStrategy:
        helm: {}
    flags:
      upgrade:
        - "--install" # remove this on skaffold v1.5.0

profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
